metadata:
  namespace: cms
spec:
  replicas: 1
  template:
    spec:
      image: ghcr.io/clcl0n/cms-image-service:latest

configuration:
  environment: staging
  otel:
    exporterOtlpEndpoint: http://otel-collector-opentelemetry-collector:4317
  connectionStrings:
    mongoDb: mongodb://mongo:27017
  messagingBroker:
    rabbitMq:
      hostName: localhost
      port: 5672
      userName: rabbitmq
      password: rabbitmq
      virtualHost: /
      ssl:
        enabled: false
  externalStorage:
    s3ObjectStorage:
      accessKey: test
      secretKey: test
      serviceUrl: http://localhost:9000
      imageBucketName: images
      forcePathStyle: true